import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "./context/supabase-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`no-scrollbar ${inter.className}`}>
        <div data-theme="nord">
          <AppWrapper>{children}</AppWrapper>
          {/* {children} */}
        </div>
      </body>
    </html>
  );
}
